# Site
title:              Milana Stojadinov
author:             ---
email:              milana.stojadinov@gmail.com
bio:
description:        "Personal blog"

# Jekyll
permalink:          /:title/
markdown:           kramdown
theme:              minima
show_excerpts:      true
sass:
  sass_dir:         _sass
  style:            compressed

header_pages:
- about/index.md

disqus_shortname:   mimimalizam-github-io
twitter_username:   mstojadinov
github_username:    mimimalizam
linkedin:           mstojadinov
