# Site
title:              Milana Stojadinov
author:             ---
email:              milana.stojadinov@gmail.com
bio:
description:

# Jekyll
permalink:          /:title/
markdown:           kramdown
theme:              minima
show_excerpts:      true
highlighter:        rouge
sass:
  sass_dir:         _sass
  style:            compressed

header_pages:
- about/index.md

google_analytics:   UA-80096404-1
disqus:
  shortname:        mimimalizam-github-io
twitter_username:   mstojadinov
github_username:    mimimalizam
linkedin:           mstojadinov
