title: Milana Stojadinov
author: mimimalizam
email: milana.stojadinov@gmail.com
description: "my blog space"

show_excerpts: true
baseurl: ""

permalink: /:categories/:title/
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
